import type {
  CanvasElement,
  ElementType,
} from "./types";
export const palette: Array<{
  type: ElementType;
  label: string;
  description: string;
}> = [
  { type: "heading", label: "Titolo", description: "Titolo principale" },
  { type: "text", label: "Testo", description: "Paragrafo di testo" },
  { type: "button", label: "Pulsante", description: "Pulsante interattivo" },
  { type: "input", label: "Campo input", description: "Campo compilabile" },
  { type: "container", label: "Contenitore", description: "Blocco grafico" },
  { type: "image", label: "Immagine", description: "Foto o grafica" },
  { type: "shape", label: "Forma", description: "Rettangolo, ellisse o linea" },
];

export const defaults: Record<ElementType, Omit<CanvasElement, "id" | "type">> = {
  heading: {
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 120,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 3,
    visible: true,
    locked: false,
    zIndex: 1,
    text: "Nuovo titolo",
    color: "#0f172a",
    background: "transparent",
    fontSize: 42,
    width: 100,
    alignment: "left",
  },
  text: {
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 120,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 3,
    visible: true,
    locked: false,
    zIndex: 1,
    text: "Inserisci qui il tuo testo.",
    color: "#334155",
    background: "transparent",
    fontSize: 18,
    width: 100,
    alignment: "left",
  },
  button: {
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 120,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 3,
    visible: true,
    locked: false,
    zIndex: 1,
    text: "Pulsante",
    color: "#ffffff",
    background: "#2563eb",
    fontSize: 16,
    width: 100,
    alignment: "left",
  },
  input: {
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 120,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 3,
    visible: true,
    locked: false,
    zIndex: 1,
    text: "Scrivi qualcosa...",
    color: "#0f172a",
    background: "#ffffff",
    fontSize: 16,
    width: 100,
    alignment: "left",
  },
  container: {
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 120,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 3,
    visible: true,
    locked: false,
    zIndex: 1,
    text: "Contenitore",
    color: "#475569",
    background: "#e2e8f0",
    fontSize: 16,
    width: 100,
    alignment: "left",
  },
  image: {
    text: "Immagine",
    color: "#475569",
    background: "#e2e8f0",
    fontSize: 16,
    width: 100,
    alignment: "center",
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 480,
    heightPx: 320,
    gridColumnStart: 0,
    gridColumnSpan: 12,
    gridRowStart: 0,
    gridRowSpan: 6,
    visible: true,
    locked: false,
    zIndex: 1,
    imageSrc: "",
    objectFit: "cover",
    borderRadius: 12,
    opacity: 100,
  },
  shape: {
    text: "Forma",
    color: "#ffffff",
    background: "#2563eb",
    fontSize: 16,
    width: 100,
    alignment: "center",
    positionMode: "grid",
    x: 40,
    y: 40,
    widthPx: 320,
    heightPx: 160,
    gridColumnStart: 0,
    gridColumnSpan: 6,
    gridRowStart: 0,
    gridRowSpan: 4,
    visible: true,
    locked: false,
    zIndex: 1,
    borderRadius: 0,
    opacity: 100,
    borderWidth: 0,
    borderColor: "#0f172a",
    rotation: 0,
    shadow: "none",
    shapeType: "rectangle",
    shapeThickness: 4,
  },
};



